Add jenkinsfile, clean up deploy
zooniverse/shakespeares_world pull request #384
Opened 2018-08-21 15:46 UTC by rogerhutchings

Add jenkinsfile for automated deploy, updated PJC, and clean up the old build tasks.

Related to https://github.com/zooniverse/AnnoTate/pull/227 and https://github.com/zooniverse/panoptes-javascript-client/pull/103

2018-08-21 16:12 UTC, adammcmaster requested changes
👍 Just one small change.

2018-08-21 16:12 UTC, adammcmaster commented on Jenkinsfile
> +    // if (BRANCH_NAME == 'staging') {
Is this supposed to be commented out? I'd guess this either needs to be uncommented, or we should remove it if it's not needed.

2018-11-20 11:53 UTC, camallen commented
@rogerhutchings is this ready to ship?

2018-11-20 12:53 UTC, rogerhutchings commented
As far as I can remember, it should be good to go!

2019-12-12 17:11 UTC, closed without merging